device_name = "Hello device"
server_ip = "https://10.30.8.245:2302"

[capability."Turn Off"]
    available = false
    type = "button"

[capability."Turn On"]
    available = true
    type = "button"

[capability."Brightness"]
    available = true
    type = "slider"
